SELECT 
    e.EMP_ID,
    e.FIRST_NAME,
    e.LAST_NAME,
    e.DEPARTMENT_NAME,
    COUNT(y.EMP_ID) AS YOUNGER_EMPLOYEES_COUNT
FROM 
    Employees e
LEFT JOIN 
    Employees y ON e.DEPARTMENT_NAME = y.DEPARTMENT_NAME AND e.AGE > y.AGE
GROUP BY 
    e.EMP_ID, e.FIRST_NAME, e.LAST_NAME, e.DEPARTMENT_NAME
ORDER BY 
    e.EMP_ID DESC;
