SELECT 
    MAX(t.SALARY) AS SALARY,
    CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS NAME,
    e.AGE,
    e.DEPARTMENT_NAME
FROM 
    transactions t
JOIN 
    employees e ON t.EMPLOYEE_ID = e.EMPLOYEE_ID
WHERE 
    DAY(t.TRANSACTION_DATE) != 1
GROUP BY 
    e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, e.AGE, e.DEPARTMENT_NAME
ORDER BY 
    SALARY DESC
LIMIT 1;
